/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class danalyzer_executor_NativeCode */

#ifndef _Included_danalyzer_executor_NativeCode
#define _Included_danalyzer_executor_NativeCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     danalyzer_executor_NativeCode
 * Method:    newArrayNative
 * Signature: ([Ldanalyzer/executor/Value;II)V
 */
JNIEXPORT jobjectArray JNICALL Java_danalyzer_executor_NativeCode_newArrayNative
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
